version: "3.9"

services:

  apache:
    build:
      context: ./apache
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:10.3
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: unless-stopped

volumes:
  db-data:
    driver: local
