version: "3.9"

services:

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/html
    networks:
      - backend

  db:
    image: mariadb:10.3
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: unless-stopped


networks:
  backend:

volumes:
  db-data:
    driver: local
